blank_issues_enabled: true
contact_links:
  - name: Contacto por correo
    url: https://fisicabit.com/#contacto
    about: Si preferís no usar GitHub, escribinos a contactfisicasimple@gmail.com (también podés usar la opción SUGERENCIAS Y ERRORES dentro de AYUDA en la página).
